name: Terraform CI

on:
  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - master
      - main

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
        TF_VAR_databricks_token: ${{ secrets.DATABRICKS_TOKEN }}
        TF_VAR_workspace_url: ${{ secrets.DATABRICKS_HOST }}
        TF_VAR_environment: dev
        run: terraform plan -var-file="environments/dev.tfvars"